language: python
python:
  - "2.7"
services:
  - postgresql
install: 
  - pip install -r reqs/dev.txt
env:
  - DJANGO_SETTINGS_MODULE="menuwatch.settings.travis"
before_script:
  - psql -c 'create database menuwatch;' -U postgres
  - python manage.py syncdb --noinput
  - python manage.py migrate
script: nosetests